apiVersion: v1

kind: Pod

metadata:
  name: myfirstapp
  labels:
    app: myfirstapp
    developer: prince
    location: utrecht
    type: database

spec:
  containers:
    - name: nginx-container
      image: nginx 

    - name: backend-container 
      image: redis
